[package]
name = "docker-ctl"
version = "0.1.0"
authors = ["matsumoto <r-matsumoto@zyyx.jp>"]

[dependencies]

[dependencies.clap]
version = "2.32"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color" ]
